import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default function DashboardPage() {
  return (
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-xl">Weekly Budget</CardTitle>
          <CardDescription>Your target vs actual spending</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold">Rp 350.000</div>
          <p className="text-xs text-muted-foreground mt-1">
            +12% from last week
          </p>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-xl">Nutrition Goal</CardTitle>
          <CardDescription>Daily target progress</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold text-green-600">85%</div>
          <p className="text-xs text-muted-foreground mt-1">
            Protein is slightly low
          </p>
        </CardContent>
      </Card>

      <Card className="md:col-span-2 lg:col-span-1">
        <CardHeader className="pb-2">
          <CardTitle className="text-xl">Saved Meal Plans</CardTitle>
          <CardDescription>Generated by AI</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold">3</div>
          <p className="text-xs text-muted-foreground mt-1">
            Active for this week
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
